name: flutter_learning_app
description: "A new Flutter project."
publish_to: "none"

version: 1.2.2+17

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^0.69.0
  flutter_localizations:
    sdk: flutter

  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8

  # 下載圖片、挑圖、存檔、分享
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  share_plus: ^10.0.0

  # 相簿圖片解析 QR 用 ML Kit
  google_mlkit_barcode_scanning: ^0.11.0
  image: ^4.5.4        # ← 原本 4.2.0，升到 4.5.4 才會一起用 archive 4.x
  zxing2: ^0.2.2       # 純 Dart ZXing QR 解碼
  archive: ^4.0.7      # ← 原本 3.6.1，升到 4.x（跟 image 對上）

  # google 登入
  google_sign_in: ^7.1.1

  # 廣告/連結開啟
  url_launcher: ^6.3.0
  open_filex: ^4.5.0
  dio: ^5.9.0
  package_info_plus: ^8.3.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_analytics: ^12.0.1

  # 網路
  connectivity_plus: ^6.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  pointer_interceptor: ^0.9.3

  # 網頁版專用
  mime: ^1.0.5

  # 手機重力水平面傾斜
  sensors_plus: ^6.0.1
  audioplayers: ^6.5.1

  # App 內部購買
  in_app_purchase: ^3.0.9
  in_app_purchase_android: ^0.3.0

  # 匯出全部檔案
  file_picker: ^8.1.2
  file_saver: ^0.2.13
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4   
  flutter_native_splash: ^2.4.7     

flutter_launcher_icons:
  android: true
  ios: true

  # 必填：兩端的來源圖
  image_path_android: assets/images/popcard.png
  image_path_ios: assets/images/popcard.png

  # ANDROID Adaptive（有就會用 Adaptive；沒支援的密度會回退到 image_path_android）
  adaptive_icon_foreground: assets/images/popcard.png
  adaptive_icon_background: "#FFFFFF"   # 或 assets/images/your_bg.png


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/popcard.png
    - assets/images/ad_banner.png
    - assets/images/pop_card_without_background.png
    - assets/images/tip_explore.png
    - assets/images/tip_explore2.png
    - assets/images/popcard01.png      # ← 新增：啟動畫面要用的圖
flutter_native_splash:
  android: true
  ios: true
  web: false           # Web 另有作法，先關掉

  color: "#FFFFFF"     # 淺色背景（可換成你的 surface）
  color_dark: "#121212"
  image: assets/images/popcard01.png
  android_gravity: center
  ios_content_mode: center

  android_12:
    image: assets/images/popcard01.png
    color: "#FFFFFF"
    color_dark: "#121212"
